# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=3)),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
