# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171109_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_form',
            name='email',
            field=models.EmailField(default='a1@as.as', max_length=10),
        ),
        migrations.AddField(
            model_name='room_form',
            name='name',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
