# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171109_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_form',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room_form',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
